# Generated by Django 3.2.13 on 2022-06-28 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_checksum', models.CharField(blank=True, max_length=100, null=True, verbose_name='hash checksum')),
                ('file_contents', models.FileField(blank=True, null=True, upload_to='user_files', verbose_name='file contents')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('activity_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='activity type')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='upload date')),
                ('data_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myreport.datafile', verbose_name='file')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
