# Generated by Django 3.2.13 on 2022-07-13 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myreport', '0003_auto_20220707_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='datafile',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='upload date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='data_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='myreport.datafile'),
        ),
    ]
